/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppCreateRouteImport } from './routes/_app.create'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as AppEditGameIdRouteImport } from './routes/_app.edit.$gameId'
import { Route as PlayGameIdIndexRouteImport } from './routes/play.$gameId.index'
import { Route as PlayGameIdWinnerRouteImport } from './routes/play.$gameId.winner'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEditGameIdRoute = AppEditGameIdRouteImport.update({
  id: '/edit/$gameId',
  path: '/edit/$gameId',
  getParentRoute: () => AppRoute,
} as any)
const PlayGameIdIndexRoute = PlayGameIdIndexRouteImport.update({
  id: '/play/$gameId/',
  path: '/play/$gameId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayGameIdWinnerRoute = PlayGameIdWinnerRouteImport.update({
  id: '/play/$gameId/winner',
  path: '/play/$gameId/winner',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/create': typeof AppCreateRoute
  '/play/': typeof PlayIndexRoute
  '/edit/$gameId': typeof AppEditGameIdRoute
  '/play/$gameId/winner': typeof PlayGameIdWinnerRoute
  '/play/$gameId/': typeof PlayGameIdIndexRoute
}
export interface FileRoutesByTo {
  '/create': typeof AppCreateRoute
  '/': typeof AppIndexRoute
  '/play': typeof PlayIndexRoute
  '/edit/$gameId': typeof AppEditGameIdRoute
  '/play/$gameId/winner': typeof PlayGameIdWinnerRoute
  '/play/$gameId': typeof PlayGameIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/create': typeof AppCreateRoute
  '/_app/': typeof AppIndexRoute
  '/play/': typeof PlayIndexRoute
  '/_app/edit/$gameId': typeof AppEditGameIdRoute
  '/play/$gameId/winner': typeof PlayGameIdWinnerRoute
  '/play/$gameId/': typeof PlayGameIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/play/'
    | '/edit/$gameId'
    | '/play/$gameId/winner'
    | '/play/$gameId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/create'
    | '/'
    | '/play'
    | '/edit/$gameId'
    | '/play/$gameId/winner'
    | '/play/$gameId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/create'
    | '/_app/'
    | '/play/'
    | '/_app/edit/$gameId'
    | '/play/$gameId/winner'
    | '/play/$gameId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PlayIndexRoute: typeof PlayIndexRoute
  PlayGameIdWinnerRoute: typeof PlayGameIdWinnerRoute
  PlayGameIdIndexRoute: typeof PlayGameIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create': {
      id: '/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/edit/$gameId': {
      id: '/_app/edit/$gameId'
      path: '/edit/$gameId'
      fullPath: '/edit/$gameId'
      preLoaderRoute: typeof AppEditGameIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/play/$gameId/': {
      id: '/play/$gameId/'
      path: '/play/$gameId'
      fullPath: '/play/$gameId/'
      preLoaderRoute: typeof PlayGameIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$gameId/winner': {
      id: '/play/$gameId/winner'
      path: '/play/$gameId/winner'
      fullPath: '/play/$gameId/winner'
      preLoaderRoute: typeof PlayGameIdWinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCreateRoute: typeof AppCreateRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEditGameIdRoute: typeof AppEditGameIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreateRoute: AppCreateRoute,
  AppIndexRoute: AppIndexRoute,
  AppEditGameIdRoute: AppEditGameIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PlayIndexRoute: PlayIndexRoute,
  PlayGameIdWinnerRoute: PlayGameIdWinnerRoute,
  PlayGameIdIndexRoute: PlayGameIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
