name: jeopardy
services:
  database:
    image: postgres:17
    environment:
      POSTGRES_USER: jeopardy
      POSTGRES_PASSWORD: jeopardy
      POSTGRES_DB: jeopardy
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jeopardy"]
      interval: 2s
      timeout: 5s
      retries: 15

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  database:
