/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as EditGameIdRouteImport } from './routes/edit.$gameId'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as PlayGameIdIndexRouteImport } from './routes/play.$gameId.index'
import { Route as PlayGameIdWinnerRouteImport } from './routes/play.$gameId.winner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EditGameIdRoute = EditGameIdRouteImport.update({
  id: '/edit/$gameId',
  path: '/edit/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayGameIdIndexRoute = PlayGameIdIndexRouteImport.update({
  id: '/play/$gameId/',
  path: '/play/$gameId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayGameIdWinnerRoute = PlayGameIdWinnerRouteImport.update({
  id: '/play/$gameId/winner',
  path: '/play/$gameId/winner',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/edit/$gameId': typeof EditGameIdRoute
  '/play/': typeof PlayIndexRoute
  '/play/$gameId/winner': typeof PlayGameIdWinnerRoute
  '/play/$gameId/': typeof PlayGameIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/edit/$gameId': typeof EditGameIdRoute
  '/play': typeof PlayIndexRoute
  '/play/$gameId/winner': typeof PlayGameIdWinnerRoute
  '/play/$gameId': typeof PlayGameIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/edit/$gameId': typeof EditGameIdRoute
  '/play/': typeof PlayIndexRoute
  '/play/$gameId/winner': typeof PlayGameIdWinnerRoute
  '/play/$gameId/': typeof PlayGameIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/edit/$gameId'
    | '/play/'
    | '/play/$gameId/winner'
    | '/play/$gameId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/edit/$gameId'
    | '/play'
    | '/play/$gameId/winner'
    | '/play/$gameId'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/edit/$gameId'
    | '/play/'
    | '/play/$gameId/winner'
    | '/play/$gameId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  EditGameIdRoute: typeof EditGameIdRoute
  PlayIndexRoute: typeof PlayIndexRoute
  PlayGameIdWinnerRoute: typeof PlayGameIdWinnerRoute
  PlayGameIdIndexRoute: typeof PlayGameIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$gameId': {
      id: '/edit/$gameId'
      path: '/edit/$gameId'
      fullPath: '/edit/$gameId'
      preLoaderRoute: typeof EditGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$gameId/': {
      id: '/play/$gameId/'
      path: '/play/$gameId'
      fullPath: '/play/$gameId/'
      preLoaderRoute: typeof PlayGameIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$gameId/winner': {
      id: '/play/$gameId/winner'
      path: '/play/$gameId/winner'
      fullPath: '/play/$gameId/winner'
      preLoaderRoute: typeof PlayGameIdWinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  EditGameIdRoute: EditGameIdRoute,
  PlayIndexRoute: PlayIndexRoute,
  PlayGameIdWinnerRoute: PlayGameIdWinnerRoute,
  PlayGameIdIndexRoute: PlayGameIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
